### ISSUE TITLE
FileNotFoundError (lgd_dataset_with_is_are)

### ISSUE THREAD

**Issue by antgr** [yoavg/bert-syntax#3]
(BERT-Syntax) ant@..:~/.../bert-syntax$ python eval_bert.py | tee  results/lgd_results_large.txt
using model: bert-large-uncased
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1248501532/1248501532 [18:31<00:00, 1123474.91B/s]
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 231508/231508 [00:00<00:00, 243357.01B/s]
Traceback (most recent call last):
  File "eval_bert.py", line 128, in <module>
    eval_lgd()
  File "eval_bert.py", line 81, in eval_lgd
    for i,line in enumerate(open("lgd_dataset_with_is_are.tsv",encoding="utf8")):
**FileNotFoundError: [Errno 2] No such file or directory: 'lgd_dataset_with_is_are.tsv'**

**Comment by antgr** [comment]
`lgd_dataset.tsv` is created by
```bash
wget http://tallinzen.net/media/rnn_agreement/agr_50_mostcommon_10K.tsv.gz
gunzip agr_50_mostcommon_10K.tsv.gz
python make_linzen_goldberg_testset.py > lgd_dataset.tsv
```

**Comment by antgr** [comment]
wiki.vocab, and  generated.tab are also needed,  (see in README section Data Files)
` wget https://raw.githubusercontent.com/TalLinzen/rnn_agreement/master/data/wiki.vocab `
` wget https://raw.githubusercontent.com/facebookresearch/colorlessgreenRNNs/master/data/agreement/English/generated.tab `
